### ISSUE TITLE
Newer then 1.22 will not start on Ubuntu 17.10

### ISSUE THREAD

**Issue by rovingrambler** [Foundry376/Mailspring#1014]
##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 17.10
...

##### What version of Mailspring are you using?
1.2.2
...

--

Nothing newer then 1.2.2 will start. I've tried 1.3, both snap and .deb and 1.4 as a snap.
On a clean install you get as far as adding an account. The App then hangs.

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No Occurs  with both Gmail and Office 365
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

/snap/bin/mailspring -V
/snap/mailspring/240/bin/desktop-launch: line 185: /home/USER/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/USER/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/240/bin/desktop-launch: line 188: /home/USER/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/240/bin/desktop-launch: line 188: /home/USER/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Running database migrations
App load time: 290ms

{"error":null}
{ Error: watch /home/USER/snap/mailspring/common/keymap.json ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1386:19)
    at Object.fs.watch (fs.js:1412:11)
    at KeymapFile.watch (/src/keymap-manager.es6:83:8)
    at KeymapManager.loadKeymaps (/src/keymap-manager.es6:131:21)
    at window.requestAnimationFrame (/src/app-env.es6:596:26)
  message: 'watch /home/USER/snap/mailspring/common/keymap.json ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/USER/snap/mailspring/common/keymap.json',
  filename: '/home/USER/snap/mailspring/common/keymap.json' } { url: 'fs.js', line: 1388, column: 5, pluginIds: [] }

---------------------------------------------------------------------------------------------------------------------------
home isn't full {yet}
$ df| grep home
/dev/mapper/vg0-home         256981444 218706704  25151156  90% /home

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...
_________________________________________________________________________________
Identical behavior in 18.04.

Running database migrations
App load time: 255ms

{"error":null}
{ Error: watch /home/USER/snap/mailspring/common/keymap.json ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1386:19)
    at Object.fs.watch (fs.js:1412:11)
    at KeymapFile.watch (/src/keymap-manager.es6:83:8)
    at KeymapManager.loadKeymaps (/src/keymap-manager.es6:131:21)
    at window.requestAnimationFrame (/src/app-env.es6:596:26)
  message: 'watch /home/USER/snap/mailspring/common/keymap.json ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/USER/snap/mailspring/common/keymap.json',
  filename: '/home/USER/snap/mailspring/common/keymap.json' } { url: 'fs.js', line: 1388, column: 5, pluginIds: [] }
__________________________________________________________________________
/dev/mapper/vg0-home         256981444 192987280  50870580  80% /home

**Comment by andrewmsboyd** [comment]
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

This worked for me, too. Anyone care to elaborate on what exactly we're doing with this command? It seems to have something to do with increasing the number of files or directories that can be monitored?

**Comment by rovingrambler** [comment]
We are increasing the limit to the number of connection to inotify which is used to monitor for file changes.

As to why why inotify is being hit so hard IDN but it's common issue with electron.

**Comment by CodeMouse92** [comment]
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
