### ISSUE TITLE
Error when composing email; had to restart app

### ISSUE THREAD

**Issue by yebo29** [Foundry376/Mailspring#1038]
##### Are there any related issues?

...

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

Version 1.4.2

--

**Bug?**

Got the below error: Error: 

`Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at commitLifeCycles (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:308)
    at b (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.mi`

Everything else was cut-off. Had to restart the app. Didn't get a screenshot; sorry.

##### Is this an email sync or connection issue?
NO

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Unsure but don't think so.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Unsure. It's the first time it happened. I was able to reopen the app and pickup where I left off. 

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
N/A
...

**Comment by bengotow** [comment]
Merging this in to #921
