### ISSUE TITLE
Failed to execute 'setStart' on 'Range' when using down arrow key in reply.

### ISSUE THREAD

**Issue by EvilJimJafar** [Foundry376/Mailspring#1080]
##### What operating system are you using?

Manjaro Gnome

##### What version of Mailspring are you using?

1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?

no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

no

--

Using the keyboard to navigate to the last line (possibly past the last line?) when replying to a message throws the following error:

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967294 is larger than the node's length (1).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:308)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at vd (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:71:249)
```
Mailspring must be closed and reopened. The message is usually saved in the drafts folder.

**Comment by pyeguy** [comment]
Ubuntu 18.04

Mailspring Pro 1.4.2 

Same issue, seems to be related to up and down arrow usage.  very frustrating when it occurs. 

Traceback below.

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidMount (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:113:13)
    at commitLifeCycles (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/snap/mailspring/244/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
```

**Comment by bengotow** [comment]
Merging this in to #921
