### ISSUE TITLE
build Mail spring code in windows

### ISSUE THREAD

**Issue by glenn2223** [Foundry376/Mailspring#1082]
##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/599

##### What operating system are you using?

Windows 10 64bit

##### What version of Mailspring are you 1.4.2

---

**Bug?**

##### Is this an email sync or connection issue?

NO

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

NO

##### Is the issue reproducible with a particular attachment, message, signature, etc?

NO

---

Followed instruction from [here](https://github.com/Foundry376/Mailspring/blob/master/CONTRIBUTING.md#build-and-run-from-source). I change directory to where my MailSpring folder is but when i run `npm install` it errors. See the below

```
2026 verbose lifecycle mailspring-root@0.0.1~postinstall: CWD: C:\Users\Glenn\Documents\GitHub\Mailspring
2027 silly lifecycle mailspring-root@0.0.1~postinstall: Args: [ '/d /s /c', 'node scripts/postinstall.js' ]
2028 silly lifecycle mailspring-root@0.0.1~postinstall: Returned: code: 1  signal: null
2029 info lifecycle mailspring-root@0.0.1~postinstall: Failed to exec postinstall script
2030 verbose stack Error: mailspring-root@0.0.1 postinstall: `node scripts/postinstall.js`
2030 verbose stack Exit status 1
2030 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
2030 verbose stack     at EventEmitter.emit (events.js:182:13)
2030 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2030 verbose stack     at ChildProcess.emit (events.js:182:13)
2030 verbose stack     at maybeClose (internal/child_process.js:962:16)
2030 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
2031 verbose pkgid mailspring-root@0.0.1
2032 verbose cwd C:\Users\Glenn\Documents\GitHub\Mailspring
2033 verbose Windows_NT 10.0.17134
2034 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2035 verbose node v10.10.0
2036 verbose npm  v6.4.1
2037 error code ELIFECYCLE
2038 error errno 1
2039 error mailspring-root@0.0.1 postinstall: `node scripts/postinstall.js`
2039 error Exit status 1
2040 error Failed at the mailspring-root@0.0.1 postinstall script.
2040 error This is probably not a problem with npm. There is likely additional logging output above.
2041 verbose exit [ 1, true ]
```

**Comment by bengotow** [comment]
For anyone running in to this, try running `node scripts/postinstall.js` on the command line by itself and see if you get a more detailed error. It might be that your system version of node is too old.
