### ISSUE TITLE
Gmail account not working in 1.0.3 on Ubuntu

### ISSUE THREAD

**Issue by tsbarnes** [Foundry376/Mailspring#110]
##### Are there any related issues?

Not that I could find

##### What operating system are you using?
Ubuntu 17.04

##### What version of Mailspring are you using?
1.0.3

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The errors in the logs are
```
[background] [info] Sleeping after exception: {"debuginfo":"/auth/token/refresh","key":"Couldn't resolve hos
t name","retryable":true,"what":"std::exception"}
```
and
```
[metadata] [info] Encountered error: {"debuginfo":"/delta/streaming","key":"Couldn't resolve host name","ret
ryable":true,"what":"std::exception"}. . Will retry in 120 sec.
```

**Comment by tsbarnes** [comment]
Notably, it doesn't happen if I downgrade to 1.0.2, and it only happens with normal Gmail, not with GApps accounts.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—this /might/ be a red-herring. We've been having some scaling issues today and I think http://id.getmailspring.com/ has been going down repeatedly for the last half hour or so. (Actually trying to fix it right now... hah.) Sorry for the hassle!

**Comment by kapad** [comment]
Okay. Just tried signing in with Gmail and faced this same issue. 

Is there any way to run mailspring with debug logging (maybe via the command line)?

I'd be happy to add the debug logs for any context that you may get from them.

**Comment by kapad** [comment]
Okay, tried again and got a different error. 

Logs: 
```
Streaming log data to /tmp/Nylas-Mail-12778.log
App load time: 265ms
Manual update check (updates.getmailspring.com/check/linux/x64/1.0.3-f82c8836/89c39284-2366-4859-9932-84ea92adb328/stable) returned 204
{ TypeError: Cannot read property 'emailAddress' of undefined
    at InitialPreferencesOptions.render (/internal_packages/onboarding/lib/page-initial-preferences.cjsx:104:81)
    at InitialPreferencesOptions.render (/internal_packages/onboarding/lib/page-initial-preferences.cjsx:1:1)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:798:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
    at ReactDOMComponent._createInitialChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:703:32)
    at ReactDOMComponent.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:522:12)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
    at ReactDOMComponent._createInitialChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:703:32)
    at ReactDOMComponent.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:522:12)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at Object.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:121:51)
    at ReactDOMComponent._reconcilerUpdateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:211:28)
    at ReactDOMComponent._updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:310:31)
    at ReactDOMComponent.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:297:12)
    at ReactDOMComponent._updateDOMChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:722:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:753:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:546:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:753:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:546:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at Object.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:211:28)
    at ReactDOMComponent._updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:310:31)
    at ReactDOMComponent.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:297:12)
    at ReactDOMComponent._updateDOMChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:722:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:753:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:560:12)
    at Object.performUpdateIfNecessary (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:156:22)
    at runBatchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:150:21)
    at ReactReconcileTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:209:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:156:16)
    at Object.batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:218:5)
    at OnboardingRoot.ReactComponent.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/lib/ReactBaseClasses.js:64:16)
    at OnboardingRoot._onStateChanged (/internal_packages/onboarding/lib/onboarding-root.jsx:60:10)
    at EventEmitter.eventHandler (/src/flux/modules/reflux-coffee.coffee:117:18)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at OnboardingStore.trigger (/src/flux/modules/reflux-coffee.coffee:125:17)
    at OnboardingStore._onMoveToPage.page [as _onMoveToPage] (/internal_packages/onboarding/lib/onboarding-store.es6:117:10)
    at OnboardingStore._onFinishAndAddAccount (/internal_packages/onboarding/lib/onboarding-store.es6:150:14)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at Object.onSuccess (/internal_packages/onboarding/lib/page-account-settings-gmail.jsx:29:23)
    at OAuthSignInPage.fetchAccountDataWithToken (/internal_packages/onboarding/lib/oauth-signin-page.jsx:123:18)
    at <anonymous>
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
undefined
undefined
undefined
undefined
undefined
undefined
{ TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:744:52)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:560:12)
    at Object.performUpdateIfNecessary (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:156:22)
    at runBatchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:150:21)
    at ReactReconcileTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:209:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:156:16)
    at Object.batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:218:5)
    at InitialPreferencesOptions.ReactComponent.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/lib/ReactBaseClasses.js:64:16)
    at /internal_packages/onboarding/lib/page-initial-preferences.cjsx:49:8
    at ELECTRON_ASAR.js:567:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) message: 'Cannot read property \'_currentElement\' of null' } { url: '/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js',
  line: 744,
  column: 52,
  pluginIds: [ 'onboarding' ] }
undefined
undefined
undefined
undefined
undefined
undefined
```
And the mailspring app is stuck on this window.
![image](https://user-images.githubusercontent.com/2017355/31425668-db846336-ae7d-11e7-8c8b-6516831e1689.png)

**Comment by kapad** [comment]
Also, where does mailspring store data locally on my machine? I want to nuke this directory and retry the setup to see if the app works.

**Comment by bengotow** [comment]
Hey @kapad — you can find that data here: https://foundry376.zendesk.com/hc/en-us/articles/115001968632-How-do-I-manually-delete-cached-mail-data-and-settings-

**Comment by tsbarnes** [comment]
This is still happening with 1.0.4
![screenshot from 2017-10-12 19-33-32](https://user-images.githubusercontent.com/429099/31523916-5cbca66e-af84-11e7-998b-6c6986523bbf.png)

**Comment by christophlandon** [comment]
Still an issue with 1.0.4. The "Successfully connected to Google" window remains open, forcing you to Quit Mailspring and re-open.

**Comment by tsbarnes** [comment]
Can we please reopen this issue? It's still occurring in 1.0.5 as well. Still the "couldn't resolve host name" error.
