### ISSUE TITLE
TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.

### ISSUE THREAD

**Issue by 10robinho** [Foundry376/Mailspring#1101]
I get this error very often in long email conversations.
Also, it's easy to reproduce it by hitting up arrow few times in any longer conversation.
I'm using Ubuntu 18.04 but I've seen it both on Mac and Windows 10.

I've seen few reports that have similar problems but no comments from developers and no fixings.

If error was produced with up arrow key then I can fix it by reloading but if it's because of long email then it's not possible to fix it and I need to open that email with other software.

I'm not sure if developers actually use this email client as I occur this at least 5 times a day. I bought premium as I have many accounts, many incoming emails and most of them are with long conversations. It would be good to have some kind of reply from devs as right now it seams that I pay for non-working software that has no support.

```
TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.
    at QuotedHTMLTransformer._removeImagesStrippedByAnotherClient (/src/services/quoted-html-transformer.es6:62:24)
    at QuotedHTMLTransformer.removeQuotedHTML (/src/services/quoted-html-transformer.es6:55:10)
    at EmailFrame._emailContent (/internal_packages/message-list/lib/email-frame.jsx:59:34)
    at EmailFrame._writeContent (/internal_packages/message-list/lib/email-frame.jsx:83:72)
    at EmailFrame.componentDidMount (/internal_packages/message-list/lib/email-frame.jsx:27:10)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at u (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
    at MessageItemBody.A.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.production.min.js:12:357)
    at _unsub._mailspringExports.MessageBodyProcessor.subscribe.processedBody (/internal_packages/message-list/lib/message-item-body.jsx:63:29)
    at retrieve.then.output (/src/flux/stores/message-body-processor.es6:97:13)
    at <anonymous>`
```

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@10robinho: Although it'd normally classify as "stale", this one is odd enough that I think it's worth double checking on now. Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team
