### ISSUE TITLE
Crash of 'onboarding' plugin : "Cannot read property 'emailAddress' of undefined"

### ISSUE THREAD

**Issue by Bouska** [Foundry376/Mailspring#112]
I'm using MailSpring **1.0.3** on **Fedora 26**. When I'm trying to add a IMAP account (I tried with a Gmail account and my uni mail account) through the onboarding process, the app crashes after clicking _Connect Account_ with the following error:

```
{ TypeError: Cannot read property 'emailAddress' of undefined
    at InitialPreferencesOptions.render (/internal_packages/onboarding/lib/page-initial-preferences.cjsx:104:81)
    at InitialPreferencesOptions.render (/internal_packages/onboarding/lib/page-initial-preferences.cjsx:1:1)
    at /usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:795:21
    at measureLifeCyclePerf (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:794:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
    at ReactDOMComponent._createInitialChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:703:32)
    at ReactDOMComponent.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:522:12)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
    at ReactDOMComponent._createInitialChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:703:32)
    at ReactDOMComponent.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:522:12)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at Object.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:121:51)
    at ReactDOMComponent._reconcilerUpdateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:206:32)
    at ReactDOMComponent._updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:310:31)
    at ReactDOMComponent.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:297:12)
    at ReactDOMComponent._updateDOMChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:722:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:753:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:546:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:753:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:546:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at Object.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:206:32)
    at ReactDOMComponent._updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:310:31)
    at ReactDOMComponent.updateChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:297:12)
    at ReactDOMComponent._updateDOMChildren (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:722:10)
    at Object.receiveComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:753:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:560:12)
    at Object.performUpdateIfNecessary (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:156:22)
    at runBatchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:150:21)
    at ReactReconcileTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:209:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/Transaction.js:156:16)
    at Object.batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:218:5)
    at OnboardingRoot.ReactComponent.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/lib/ReactBaseClasses.js:64:16)
    at OnboardingRoot._onStateChanged (/internal_packages/onboarding/lib/onboarding-root.jsx:60:10)
    at EventEmitter.eventHandler (/src/flux/modules/reflux-coffee.coffee:117:18)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at OnboardingStore.trigger (/src/flux/modules/reflux-coffee.coffee:125:17)
    at OnboardingStore._onMoveToPage.page [as _onMoveToPage] (/internal_packages/onboarding/lib/onboarding-store.es6:117:10)
    at OnboardingStore._onFinishAndAddAccount (/internal_packages/onboarding/lib/onboarding-store.es6:150:14)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at then.validated (/internal_packages/onboarding/lib/decorators/create-page-for-form.jsx:120:29)
    at <anonymous>
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

**Comment by Bouska** [comment]
I just tried again with a gmail account, in dev mode this time, and it also crashes, with the same backtrace.

**Comment by bengotow** [comment]
Hey! This should be fixed now, but it's odd this happened in the first place. Will re-open if we see this again.

**Comment by arthurlogilab** [comment]
Getting this same bug with version 1.7.4

```
Running database migrations
App load time: 404ms

{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.4-d54ff730/e9d77574-dcc3-409a-a2c2-e65957b9db50/stable) returned 204
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
Raven: 429 - undefined
```

And 

```
 dpkg -l mailspring                                                                     mar. 25 févr. 2020 11:49:48 CET
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-========================================================
ii  mailspring                1.7.4             amd64             The best email app for people and teams at work
```

**Comment by franciscomemoli** [comment]
Same problem here.
First I tried  to add an hotmail account and didn't work. Then I tried with an gmail account and works. After that I tried to add a second account and didn't work, neither hotmail nor IMAP/SMTP nor gmail. 
Then I tried to add the account in dev mode and I got this error

![image](https://user-images.githubusercontent.com/5726670/75258484-44a41800-57c5-11ea-83b6-7a7185d21d76.png)

**Comment by asceel** [comment]
Hi!
I have just installed the app using snap on Manjaro. I registered an account (Mailspring ID), connected an account then nothing shows up. Blank white screen.

![image](https://user-images.githubusercontent.com/58683078/75397528-2266e300-5908-11ea-9031-6b0f152f7075.png)
If I quit the app and relaunch it, I'm back to connect an email account screen. And the exact same problem happens again. Looks like it doesn't add an account at all.

**Comment by LukasLen** [comment]
> Hey! This should be fixed now, but it's odd this happened in the first place. Will re-open if we see this again.
@bengotow 

This should be re-opened. Same here:
```
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }

**Comment by nachitog83** [comment]
Same here!. having this issue since yesterday.

`Running Setup
{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.4-d54ff730/anonymous/stable) returned 204
{ TypeError: Cannot read property 'emailAddress' of undefined at _AccountStore.addAccount file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)`

**Comment by hamzawix** [comment]
Why this issue was closed? I didn't see any resolution so reopen it! 
I experienced the same behavior today when I try to add my office365 corporate account 
TypeError: Cannot read property 'emailAddress' of undefined

**Comment by aefde** [comment]
I have same problem on Ubuntu 16.04 and 18.04. I abandonned mailspring.

**Comment by mwehnert** [comment]
I have the same problem as well on Elementary OS 5.1 Hera.

```
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
Raven: 429 - undefined
```

**Comment by johackim** [comment]
I have this issue too on Arch Linux with Mailspring 1.7.4

**Comment by pankus** [comment]
Same for me. Ubuntu 18.04 with Mailspring 1.7.4-d54ff730 installed by .deb package

> { TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }

**Comment by nachitog83** [comment]
Hi everyone... i found a workaround (maybe not the most comfortable one, but it's something).

I downgraded mailspring to 1.7.2 (uninstalled 1.7.4 and installed 1.7.2, all manually, deb packages).

Added IMAP accounts needed with no problem (i have no issues with Gmail accounts in 1.7.4).

Then upgraded to 1.7.4, also with deb package.

Hope this helps for now, until the support community develops a permanent solution to 1.7.4.

**Comment by franciscomemoli** [comment]
I can't believe how obvious that workaround is and I didn't thought about.
That works for me thanks!

**Comment by farah-zaidi** [comment]
nachitog83 How to install version 1.7.2, i have ubunto 18.4 and i download source code 1.7.2 but there is no instruction in readme to install from code source? thnx

**Comment by working-name** [comment]
@nachitog83 it doesn't solve it for everyone. In my case 1.7.2 and 1.7.1 although they don't error out, the account is never added.

**Comment by AlexanderBF** [comment]
Added the line
`return account;`
at the end of the function **finalizeAndValidateAccount**
in the file "**app/internal_packages/onboarding/lib/onboarding-helpers.ts**"
fixed the issue for me.

**Comment by SirBigoo** [comment]
I did the same as @AlexanderBF : it works !

**Comment by AzagraMac** [comment]
**OS:** Debian 10.3 Buster 64bit
**Mailspring:** 1.7.4
**Installation method:** from [https://getmailspring.com/download](https://getmailspring.com/download) with the 64-bit .deb file
**Case:** Error, it is not possible to add an IMAP / iCloud account, despite the fact that in graphic mode it does not report an error, looking at the log, it returns this error.

```sh
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

**Comment by RoySRC** [comment]
I get the same error:

`{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
`

**Comment by vcvitaly** [comment]
Installing 1.7.5 solved that for me
`sudo snap install mailspring --edge`

**Comment by Darkducat** [comment]
1.7.5 ?

**Comment by davenorthcreek** [comment]
I am happily using snap except that it can't read files in my /data partition, so I tried to install 1.7.4 from the .deb file on Kubuntu 18.04 and I'm seeing the same issue when trying to add IMAP accounts.
```
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

**Comment by vcvitaly** [comment]
> 1.7.5 ?
> […](#)
> Le 6 avr. 2020 à 17:09, vcvitaly ***@***.***> a écrit : ﻿ Installing 1.7.5 solved that for me sudo snap install mailspring --edge — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, I'm using ubuntu, not sure how you get it installed on your OS

![image](https://user-images.githubusercontent.com/6715363/78632927-f34d7500-78a8-11ea-8b6d-132abb24c76f.png)

**Comment by vcvitaly** [comment]
> I am happily using snap except that it can't read files in my /data partition, so I tried to install 1.7.4 from the .deb file on Kubuntu 18.04 and I'm seeing the same issue when trying to add IMAP accounts.
> 
> ```
> { TypeError: Cannot read property 'emailAddress' of undefined
>     at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
>     at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
>     at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
>     at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
>     at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
>     at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
>     at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
>   message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
> ```

You can manage app permissions in snap (on Ubuntu that can be done in Software app)
Have you tried that?

**Comment by davenorthcreek** [comment]
I was able to find that app permission, but what fixed the issue was moving the mounted partition into the /media parent directory instead of just mounting it at /data.  Once I did that the partition became visible to Snap's sandbox.

**Comment by davenorthcreek** [comment]
So I'm able to continue to use the Snap version of Mailspring while waiting for version 1.7.5.  At that point I will investigate how to migrate from a snap version to a deb version without losing all of my configured accounts.

**Comment by AzagraMac** [comment]
1.7.5 .deb file not found
