### ISSUE TITLE
Can't Leave Developer Mode

### ISSUE THREAD

**Issue by themanofmanyways** [Foundry376/Mailspring#1120]
##### Are there any related issues?

There's one here https://github.com/Foundry376/Mailspring/issues/384 . But that was for windows 10.

##### What operating system are you using?

Linux. Linux Mint to be precise.

##### What version of Mailspring are you using?

1.4.2
--

**Bug?**

##### Is this an email sync or connection issue?

Neither

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screenshot from 2018-10-09 21-42-08](https://user-images.githubusercontent.com/44006164/46697857-830b5800-cc0d-11e8-8a35-807cc1c40b05.png)

Essentially I tried to make my own theme using the themer, and after following the instructions to open in developer mode, I got confused. The app opened as though it was reset (I had put several emails on it prior to this) and so I closed it and reopened it only to see the above screen. Please help.

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Mailspring is the first I've really used.

Please help. I was quite excited about this client in particular since it looked the nicest.

**Comment by bengotow** [comment]
Hey thanks for checking out Mailspring! I'm glad you're giving theming a shot - sorry you've run in to trouble. If you click the red "X" in the toolbar of the developer panel (beside Network, Performance, etc.) it'll show a panel at the bottom with a bit more information about what happened.

Your best bet is probably to quit Mailspring and re-launch it. When you start it up again, it should complain about an invalid theme and over to reset you to the default one. Knowing what is in that hidden error would definitely help narrow down what to do next!

**Comment by themanofmanyways** [comment]
@bengotow I've tried reinstalling the app even but there's no difference from before. Even restoring an earlier system snapshot doesn't seem to help so I'm stumped as to what it could be. I relauched the application as you said but unfortunately, it didn't change anything. I've tried to enlarge the app so you can clearly see the error message below though.

![screenshot from 2018-10-16 18-21-44](https://user-images.githubusercontent.com/44006164/47035005-c9623900-d170-11e8-80a0-7e1f9af67c69.png)

Copying and pasting below:

_index.js:26 Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('theme-Fonce Rouge') contains HTML space characters, which are not valid in tokens.
    at ThemeManager.activateThemePackage (/src/theme-manager.es6:136:29)
    at new AppEnvConstructor (/src/app-env.es6:95:17)
    at Object.<anonymous> (/src/secondary-window-bootstrap.es6:18:17)
    at Object.<anonymous> (/src/secondary-window-bootstrap.es6:26:1)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at setupWindow (file:///usr/share/mailspring/resources/app.asar/static/index.js:47:3)
    at window.onload (file:///usr/share/mailspring/resources/app.asar/static/index.js:75:5)_

"Fonce Rouge" is the name I originally gave the theme though I later realized it had to be named "general" or something like that and I changed it.

**Comment by CodeMouse92** [comment]
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
