### ISSUE TITLE
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#1190]
Hello team !

spec : win10
mailspring : 1.5.1-da141eaf with dark theme

I always had this behavior from Mailspring :

- write a mail (by answering on the quic reply form)
- just write and go in the mail, and then sometimes randomly I have this (screenshot attached)
- impossible to recover, so I have to restard mailspring (I don't loose what I wrote though)

It happens now more than before, but also the error message change :
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).

Please fix this, it's incredibly annoying :)

All the best,

![image](https://user-images.githubusercontent.com/5172593/47644335-234e0000-db6e-11e8-8761-2793eaca36b8.png)

**Comment by KristerV** [comment]
ugh.. this just hit me too..

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967294 is larger than the node's length (1).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at Ki (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232:135)
    at de (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)
```

![image](https://user-images.githubusercontent.com/2750622/48357150-8ed0bb00-e6a0-11e8-8453-6a71ba54f118.png)

Arch Linux
MailSpring 1.5.2-31660462 (would be helpful if i could copy-paste the version instead of typing it :D )

I took the log out of the console also: https://pastebin.com/tEqZw8fW

**Comment by Lyptik** [comment]
happens in average once every one or two days for me (yes I write a lots of mails !)

**Comment by klawson4311** [comment]
Ditto:
`Error: Failed to execute 'setStart' on 'Range': The offset 4294967294 is larger than the node's length (109).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at Ki (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232:135)
    at de (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)`

Lose steps to repeat:   
1) Begin editing the email inline (not as a pop-out).  
2) Navigate using the keyboard arrow-keys (often the up key causes this for me).

I'm using a custom theme, so I'm not sure it has anything to do with the dark-theme.

**Comment by Lyptik** [comment]
+1, same steps and dark theme as well

Le lun. 26 nov. 2018 à 19:55, klawson4311 <notifications@github.com> a
écrit :

**Comment by rgsilva** [comment]
Happens to me as well, but not in the dark theme. Both on Linux (Ubuntu 18.04.1 LTS) and Windows (10, don't remember the build right now). All my systems seem to be affected by this issue.

Mailspring Version: 1.5.3-420ce003

**Comment by danieldraper** [comment]
This error has haunted me for a little while now.

This occurred while navigating around using the keyboard while finishing writing a reply which has been a draft for a few days.

**Mailspring version** 1.5.3
**Theme** Light
**OS** macOS Mojave (10.14.1)

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at Ki (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232:135)
    at de (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)
```

**Comment by jacobbarrow** [comment]
Also happening on Ubuntu Budgie 18.04, don't think it's OS dependent

**Comment by fquinner** [comment]
Just happened to me on linux :(

**Comment by xclabit** [comment]
Same here. Another way to reproduce this problem is in: https://github.com/Foundry376/Mailspring/issues/727#issuecomment-462114521

**Comment by jcrawford888** [comment]
As a work around I discovered if you toggle the reading pane off then on again the error will be cleared.

1. View -> Reading Pane Off
2. View -> Reading Pane On

Hopefully that helps until the bug can be fixed.

Mail Spring version: 1.5.6-4cb1851b

**Comment by tincho** [comment]
Hi there.
This just happened to me. 
I'm running Ubuntu 18.04 and yesterday I updated to 1.5.7 via .deb 
While writing a reply, I hit the up arrow key and the view/reply panel now shows nothing but this message (until I restart Mailspring), any mail I choose, the view panel shows that message.

**Comment by xclabit** [comment]
> As a work around I discovered if you toggle the reading pane off then on again the error will be cleared.
> 1. View -> Reading Pane Off
> 2. View -> Reading Pane On

@jcrawford888 Unfortunately, the above didn't work for me in clearing the error in MailSpring 1.5.7-2057ca30.

**Comment by aapit** [comment]
Unfortunately, this happens to me with a specific email containing some _nested quotes_ (from a previous mail in the thread). Toggling the reading pane does clear the error when I'm focused on other mails, but even after a restart, this particular email keeps triggering the error.
It doesn't contain any heavy images or whatever, it's just a text conversation in html format with quotes.

I'm using the Snap version of **MailSpring 1.5.7-2057ca30**
on **Ubuntu 18.04.2 LTS**
running **Gnome 3.28.2**

**Comment by ASeatonSpatial** [comment]
This is happening to me as well every now and then.  Haven't noticed any pattern yet, it has happened when I am drafting an email or just reading.  

Toggle reading pane on off clears the error. 

I am on Ubuntu 18.04.1 LTS and using snap version of MailSpring 1.5.7-2057ca30

**Comment by bengotow** [comment]
Hey folks I'm going to merge this in to #921. I've been tracking this for a while and I'm hoping it can be fixed soon. The slate-react project that powers the text editor has come a long way, but there were a few performance regressions that were blocking us from upgrading. Will see if they've been resolved!

**Comment by evaristorivi** [comment]
Me too!

Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at Ki (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232:135)
    at de (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)

**Comment by danyal14** [comment]
I am facing the same issue, where our editors are getting this issue randomly. That is quite hard to debug or track.

Is this issue solved?

We are using CDN 
https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js

domconverter.js:280 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 158 is larger than the node's length (157).
    at rr.viewRangeToDom (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:168912)
    at js.scrollToTheSelection (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:194120)
    at ro.<anonymous> (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:368982)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at ro.<anonymous> (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:367750)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at es.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182838)
    at es.onDomEvent (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182970)
    at dr.listenTo.useCapture (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182749)
    at dr.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
viewRangeToDom @ domconverter.js:280
scrollToTheSelection @ view.js:377
(anonymous) @ delete.js:42
fire @ emittermixin.js:204
(anonymous) @ deleteobserver.js:54
fire @ emittermixin.js:204
fire @ domeventobserver.js:96
onDomEvent @ keyobserver.js:28
listenTo.useCapture @ domeventobserver.js:79
fire @ emittermixin.js:204
n @ emittermixin.js:235
domconverter.js:280 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 158 is larger than the node's length (157).
    at rr.viewRangeToDom (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:168912)
    at js.scrollToTheSelection (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:194120)
    at ro.listenTo.priority (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:358602)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at ro.<anonymous> (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:358255)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at es.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182838)
    at es.onDomEvent (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182970)
    at dr.listenTo.useCapture (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182749)
    at dr.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
viewRangeToDom @ domconverter.js:280
scrollToTheSelection @ view.js:377
listenTo.priority @ enter.js:49
fire @ emittermixin.js:204
(anonymous) @ enterobserver.js:31
fire @ emittermixin.js:204
fire @ domeventobserver.js:96
onDomEvent @ keyobserver.js:28
listenTo.useCapture @ domeventobserver.js:79
fire @ emittermixin.js:204
n @ emittermixin.js:235
utils.js:37 Uncaught TypeError: Cannot read property 'is' of undefined
    at rh (utils.js:37)
    at kh._onMousedown (widget.js:123)
    at ro.<anonymous> (widget.js:90)
    at ro.fire (emittermixin.js:204)
    at wh.fire (domeventobserver.js:96)
    at wh.onDomEvent (mouseobserver.js:28)
    at dr.listenTo.useCapture (domeventobserver.js:79)
    at dr.fire (emittermixin.js:204)
    at HTMLDivElement.n (emittermixin.js:235)
rh @ utils.js:37
_onMousedown @ widget.js:123
(anonymous) @ widget.js:90
fire @ emittermixin.js:204
fire @ domeventobserver.js:96
onDomEvent @ mouseobserver.js:28
listenTo.useCapture @ domeventobserver.js:79
fire @ emittermixin.js:204
n @ emittermixin.js:235
5domconverter.js:280 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 158 is larger than the node's length (157).
    at rr.viewRangeToDom (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:168912)
    at js.scrollToTheSelection (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:194120)
    at ro.<anonymous> (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:368982)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at ro.<anonymous> (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:367750)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at es.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182838)
    at es.onDomEvent (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182970)
    at dr.listenTo.useCapture (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182749)
    at dr.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
