### ISSUE TITLE
New message compose crashes

### ISSUE THREAD

**Issue by guidov** [Foundry376/Mailspring#1314]
##### Are there any related issues?

...

##### What operating system are you using?

...

##### What version of Mailspring are you using?

...

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by guidov** [comment]
Hi,
Occasionally when I'm writing an email (I had some links in it) , after a while it crashes and I loose my email. The box where the tread is just has this sort of error text in it:

Error: Failed to execute 'setStart' on 'Range': The offset 4294967292 is larger than the node's length (1).
    at findDOMRange (/snap/mailspring/309/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/snap/mailspring/309/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/snap/mailspring/309/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/snap/mailspring/309/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/snap/mailspring/309/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/snap/mailspring/309/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at Ki (/snap/mailspring/309/usr/share/mai

I can't get rid of the corrupted composed email also.
I can't read any other emails after this happens:
I have to reinstall mailspring after this happens.

Frustrating , because it happens after I have spent a long time composing an email.

**Comment by guidov** [comment]
Sorry this is a repeat of #1190

**Comment by bengotow** [comment]
Merging in to #921
