### ISSUE TITLE
I get a error when I am using mailspring

### ISSUE THREAD

**Issue by jerry79** [Foundry376/Mailspring#1406]
OS: Deepin Linux 15.9,
Mailspring ver: 1.5.7
Error Message as below:

Error: Unable to find a DOM node for "20378". This is often because of forgetting to add `props.attributes` to a custom component.
    at findDOMNode (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-node.js:27:11)
    at findDOMPoint (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-point.js:25:38)
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:30:43)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/usr/share/mailspring/resources/app.asar/

**Comment by bengotow** [comment]
Merging this in to #1190
