### ISSUE TITLE
Crash on MacOS

### ISSUE THREAD

**Issue by wesleycoder** [Foundry376/Mailspring#1456]
##### Are there any related issues?
Didn't found something like this.

##### What operating system are you using?
MacOS

##### What version of Mailspring are you using?
1.6.1

--

**Bug!**

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

I don't know if it is a one time bug, but I'm reporting it in the case it affects someone else.

Right after the last update completed today the preview panel for emails crashed showing the following error:
![image](https://user-images.githubusercontent.com/22945955/55636761-f3003280-5799-11e9-8ebe-1d48f272da4b.png)
```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967294 is larger than the node's length (1).
    at findDOMRange (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at Ki (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232:135)
    at de (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)
```

Restarting Mailspring did got the error away, and I couldn't simulate it again.

**Comment by bengotow** [comment]
Hey! This should be fixed soon when we upgrade Slate. Stay tuned! #921
