### ISSUE TITLE
[Bug] Rendering email fails with many email recipients

### ISSUE THREAD

**Issue by shaunmolloy** [Foundry376/Mailspring#1511]
##### Are there any related issues?
None

##### What operating system are you using?
Ubuntu 18.10

##### What version of Mailspring are you using?
1.6.1

---

**Bug?**

##### Is this an email sync or connection issue?
N/A

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
N/A

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Sent email to over 70 people in CC.
It attempts to load, while hanging,
then shows the following:

**Screenshot:**

![Screenshot from 2019-05-29 15-19-35](https://user-images.githubusercontent.com/8168925/58569600-53f23700-822e-11e9-910e-845f6da47d85.png)

**Stacktrace:**

```
Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ea (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:13:316)
    at r (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at xg (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:212:130)
    at Object.enqueueSetState (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:223)
    at _a.Component.setState (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.development.js:373:16)
    at DraftEditingSession._sessionUnlisten.session.listen (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/decorators/inflates-draft-client-id.tsx:74:16)
    at EventEmitter.eventHandler (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/global/mailspring-store.ts:128:23)
    at EventEmitter.emit (events.js:182:13)
    at EventEmitter.emit (domain.js:442:20)
    at DraftEditingSession.trigger (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/global/mailspring-store.ts:141:26)
    at DraftEditingSession.changeSetApplyChanges.changes [as changeSetApplyChanges] (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/draft-editing-session.ts:469:10)
    at Object.onAddChanges (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/draft-editing-session.ts:197:35)
    at DraftChangeSet.add (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/draft-editing-session.ts:74:20)
    at Object.onChange (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/composer/lib/composer-view.tsx:263:38)
    at Object.ComposerEditor.onChange.nextValue [as onChange] (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/components/composer-editor/composer-editor.tsx:207:16)
    at Editor.flushChange (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/editor.js:352:20)
    at Editor.componentDidUpdate (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/editor.js:335:12)
    at Hi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at ii (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:214:252)
    at xg (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:212:94)
    at Object.enqueueSetState (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:223)
    at MessageList.Component.setState (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.development.js:373:16)
    at _MessageStore.MessageList._onChange (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/message-list/lib/message-list.tsx:367:10)
    at EventEmitter.eventHandler (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/global/mailspring-store.ts:128:23)
```

**Comment by bengotow** [comment]
Hey! Thanks for reporting this, sorry for the delay! It looks like this is caused by Mailspring trying to size all of the participant "tokens" in the text field, and doing it one by one. I'll see if I can reproduce this today.

**Comment by CodeMouse92** [comment]
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
