### ISSUE TITLE
Bug: Cannot read property

### ISSUE THREAD

**Issue by shanerbo** [Foundry376/Mailspring#1830]
Cannot connect smtp account

Running database migrations
App load time: 132ms

{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.4-d54ff730/d67bb060-df84-4ab5-a37f-85f4e6ad0dfb/stable) returned 204
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  **message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }**

**Comment by franckadil** [comment]
Hi, I can reproduce easily when adding a new Microsoft 365 account on all platforms

- Tested Microsoft Windows 10
- Mac OS Mojave
- Fedora Linux
- Ubuntu and Debian Linux
- Arch and Manjaro Linux

I get a white screen:
![image](https://user-images.githubusercontent.com/42721509/75613895-ebc0e080-5b32-11ea-8ef6-0ab24812fb9f.png)


```
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

Regards,
Franck

**Comment by shanerbo** [comment]
same here

**Comment by samiuvic** [comment]
same on elementary OS 5.1.2 hera

**Comment by grginho** [comment]
message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }

Debian 10

**Comment by MalteKiefer** [comment]
see #1817

**Comment by pashtet422** [comment]
same here. Fedora 31

**Comment by pankus** [comment]
#112

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this and submitting a fix - I'm sorry it's taken me so long to ship a build with the changes. I honestly can't believe it's April already. I'm doing QA tonight and I'll ship the 1.7.5 release with the patch ASAP tomorrow!
