### ISSUE TITLE
Bug: Can't add IMAP mail account.

### ISSUE THREAD

**Issue by repiatx** [Foundry376/Mailspring#1903]
I cannot add IMAP mail account. It says 'adding' after that it closes nothing happens.

**Setup: (please complete the following information):**
 - OS: Windows 10
 - Mailspring Version: 1.7.4-d54ff730

**Comment by skonsoft** [comment]
Hello, i have the same problem under UBUNTU.

When i add the email account, i got the screen telling that it's was added but nothing happen. Launching mailspring in command line i get this error:

```
skander@skander-XPS-13-7390:~$ mailspring 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 147ms

{"error":null}
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/snap/mailspring/440/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

### OS: UBUNTU 19.10
### mailspring: 1.7.4-d54ff730

**Comment by idp001** [comment]
i have the same problem and can't add office365 mail account

**Comment by jaschadub** [comment]
I have this issue as well. I do not mind paying to support the development but when I can't use for something as simple as a POP/IMAP account it makes me wonder. It seems like you could do a build with a fix but none since Feb 24th.

**Comment by Miyazono1** [comment]
i've been having this same issue for almost a month now. i was hoping they'd put out an update relatively quickly, but there hasn't been one yet. my main email is my IMAP, so i'm not even able to see most of my emails using this right now.

**Comment by Marco22874** [comment]
Clone 
https://github.com/Foundry376/Mailspring/issues/1848

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I'm really sorry it's taken so long for the fix in #1876 to get shipped. I will push out a 1.7.5 release tomorrow. 

I think we can close it as a dup of #1848 but I'll keep it open until 1.7.5 ships for here for visibility. Thanks everyone for the comments and help triaging!

**Comment by skonsoft** [comment]
@bengotow  Thank you ! i was really blocked to send invoice to my client. Please be careful next time to not break the basic features as it will costs money for us. 

To support you, i will take the pro version.

Good job, we support you :)

**Comment by jaschadub** [comment]
I can attest that it is working now to add IMAP in 1.7.5version. Thanks for fixing it!

**Comment by skonsoft** [comment]
Me too, i confirm that it works perfectly on the 1.7.5 snap version.

OS: UBUNTU 19.10

**Comment by repiatx** [comment]
Yes it work great! thx.
