### ISSUE TITLE
Bug: node-gyp dev dependency missing

### ISSUE THREAD

**Issue by cnmicha** [Foundry376/Mailspring#2106]
**Describe the bug**
In the package.json file, the node-gyp package is missing as a dev dependency.
Executing `npm run postinstall` on Linux fails.

**To Reproduce**
1. Checkout latest master branch on a Linux machine
2. Run `npm install`

The following error message occurs during the postinstall script:

```
> mailspring-root@0.0.1 postinstall /home/myuser/dev/Mailspring
> node scripts/postinstall.js


-- Clearing app/node_modules --

-- Running npm install in ./app with electron config --

> windows-quiet-hours@1.2.7 install /home/myuser/dev/Mailspring/app/node_modules/windows-quiet-hours
> node-gyp rebuild

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/myuser/dev/Mailspring/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

> runas@3.2.5 install /home/myuser/dev/Mailspring/app/node_modules/runas
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=4.2.2 runtime=electron arch=x64 platform=linux)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/myuser/dev/Mailspring/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-quiet-hours@1.2.7 (node_modules/windows-quiet-hours):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-quiet-hours@1.2.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! runas@3.2.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2020-07-29T21_21_19_690Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailspring-root@0.0.1 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mailspring-root@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The package node-gyp cannot be found.

As a workaround, you can run `npm i --dev node-gyp` followed by `npm run postinstall`. Then, everything works as expected.

**Expected behavior**
All packages install, postinstall script is executed successfully

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04.1
 - Mailspring Version: 1.7.8

**Comment by bengotow** [comment]
Hey! Thanks for reporting this, this seems like a good addition to me - I'm not sure why it works for me actually, it may be that there are prebuilt binaries on macOS and Windows so the postinstall code never falls through to trying to build from scratch.
