### ISSUE TITLE
Lag issue / black font since new version

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#556]
Win 10 
V 1.1.0-7563
black theme
4 emails synced

Since update from a few days ago, got a lot of freeze and lags, and also my font is now black on black when writing or replying to email.

Changing to white then to black did not solve the problem.

Will revert back to the old version meanhile.

**Comment by benkuper** [comment]
+1 on the black font, there were already problems when copying/pasting text, sometimes it would force the font style to be black and then paste black text on dark editor.
Now, with the rich text editor, font appears black always.
I guess there should be a "no style" default state that would choose automatically the good color depending on the theme (like it was before this version).
And we also should be able to clear the style of a font if we pasted some styled text.

**Comment by hacknug** [comment]
+1 to the lag issue.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - the black text issue has been fixed on master (it's related to the new font color picker...) and the next update will ship in the next day or two. The lag issue is interesting - I'll see if I can reproduce it. In the next version we're moving to React 16 and Electron 1.8 which should improve performance overall and I think that'll improve things quite a bit.

**Comment by Lyptik** [comment]
Thanks !
I'm not quitte sure but the lag might be related to the dark theme. Since I switched to the darkside (theme) it did not occur much.

**Comment by bengotow** [comment]
Oh interesting! That's super helpful - I'll look and see if the dark theme is doing anything that might impact performance. Depending on your GPU, it's possible that inverting images or using drop shadows, etc. has an effect.

**Comment by bengotow** [comment]
The fix for the black font issue has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy! Gonna close this and I'll investigate the lag in the dark theme separately.

**Comment by hacknug** [comment]
Mine's lagging when using the light theme.

**Comment by bengotow** [comment]
Hey @hacknug —can you elaborate a bit? Is it laggy when creating / deleting a reply or when you type into the message body, or just in general when moving through the UI? (There isn't any automated performance instrumentation in the app). I've identified the source of lag when creating new replies and that should be improved in the next version or two.

**Comment by hacknug** [comment]
Here's a short video showing weird behavior. I right clicked _podais_ to add the accent it was missing but the corrected word got added at the beginning of the message and I was unable to select, type, delete anything until I switched messages.

https://streamable.com/36pvv

**Comment by hacknug** [comment]
Also I just got this error while writing an email. Wasn't doing anything fancy or weird but I also had some typos and I was right-clicking to autocorrect them.

```
TypeError: Cannot read property 'data' of null
    at FloatingEmojiPicker (/src/components/composer-editor/emoji-plugins.jsx:77:18)
    at beginWork (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:310)
    at d (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:93)
    at f (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:417)
    at g (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at m (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:173)
    at w (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at vd (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:71:249)
```

**Comment by shalom938** [comment]
Same issue with latest update 1.5.4 on windows 10. black fonts in dark theme and also on copy paste.
