### ISSUE TITLE
No window!!!

### ISSUE THREAD

**Issue by cyberdemon8** [Foundry376/Mailspring#587]
##### What operating system are you using?
Mac OS High  Sierra 10.13.3

##### What version of Mailspring are you using?
V 1.1.1

--

**Bug?**
after upgrade from 1.1.0 no window showing on launch mailspring... only "about window" showing using menu. Tried reinstall, no success.

**UPDATE**
uninstalled, deleted all files from ~/Library/Application Support/Mailspring, reinstalled and Mailspring run correctly...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this is no good at all. I'll see if I can reproduce it. If this happens again definitely let me know - I think it's possible this happened because you launched Mailspring directly to the drafts screen and ran into #590 above.

**Comment by GXGOW** [comment]
I also have this issue, only I'm running the snap-version on Arch Linux. It worked the first time I installed and configured it, but now it won't show up anymore. The background service is running fine though.
Other snaps are also working fine so I guess that's not the issue either.

**Comment by maorodribu** [comment]
the same thing happens to me but I have not tried to solve it

App load time: 426ms
Manual update check (updates.getmailspring.com/check/linux/x64/1.1.2-8ae17eae/76024c95-2d75-499d-8885-a3b65bdd4094/stable) returned 204
{ Error: watch /home/mrodriguez/.config/Mailspring/keymap.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at KeymapFile.watch (/src/keymap-manager.es6:72:8)
    at KeymapManager.loadKeymaps (/src/keymap-manager.es6:120:21)
    at window.requestAnimationFrame (/src/app-env.es6:596:26)
  message: 'watch /home/mrodriguez/.config/Mailspring/keymap.json ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/mrodriguez/.config/Mailspring/keymap.json',
  filename: '/home/mrodriguez/.config/Mailspring/keymap.json' } { url: 'fs.js', line: 1396, column: 5, pluginIds: [] }
Raven: 429 - Creation of this event was denied due to rate limiting
{ Error: watch /home/mrodriguez/.config/Mailspring/keymap.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at KeymapFile.watch (/src/keymap-manager.es6:72:8)
    at KeymapManager.loadKeymaps (/src/keymap-manager.es6:120:21)
    at window.requestAnimationFrame (/src/app-env.es6:596:26)
  message: 'watch /home/mrodriguez/.config/Mailspring/keymap.json ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/mrodriguez/.config/Mailspring/keymap.json',
  filename: '/home/mrodriguez/.config/Mailspring/keymap.json' } { url: 'fs.js', line: 1396, column: 5, pluginIds: [] }
Raven: 429 - Creation of this event was denied due to rate limiting
{ Error: watch /home/mrodriguez/.config/Mailspring/templates ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at TemplateStore.watch (/internal_packages/composer-templates/lib/template-store.es6:55:26)
    at TemplateStore._fs2.default.exists.exists (/internal_packages/composer-templates/lib/template-store.es6:36:14)
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
  message: 'watch /home/mrodriguez/.config/Mailspring/templates ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/mrodriguez/.config/Mailspring/templates',
  filename: '/home/mrodriguez/.config/Mailspring/templates' } { url: 'fs.js',
  line: 1396,
  column: 5,
  pluginIds: [ 'composer-templates' ] }
Raven: 429 - Creation of this event was denied due to rate limiting

**Comment by lucysan** [comment]
I can confirm this also happens on Arch Linux.
Configuration and login window works, but once you finish config this happens:

```f0ff@ecorp ~ % mailspring 
Running database migrations
App load time: 167ms

Running Setup
{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.1.3-27dcee2f/anonymous/stable) returned 200
{ Error: watch /home/f0ff/.config/Mailspring/keymap.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at KeymapFile.watch (/src/keymap-manager.es6:83:8)
    at KeymapManager.loadKeymaps (/src/keymap-manager.es6:131:21)
    at window.requestAnimationFrame (/src/app-env.es6:596:26)
  message: 'watch /home/f0ff/.config/Mailspring/keymap.json ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/f0ff/.config/Mailspring/keymap.json',
  filename: '/home/f0ff/.config/Mailspring/keymap.json' } { url: 'fs.js', line: 1396, column: 5, pluginIds: [] }
{ Error: watch /home/f0ff/.config/Mailspring/keymap.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at KeymapFile.watch (/src/keymap-manager.es6:83:8)
    at KeymapManager.loadKeymaps (/src/keymap-manager.es6:131:21)
    at window.requestAnimationFrame (/src/app-env.es6:596:26)
  message: 'watch /home/f0ff/.config/Mailspring/keymap.json ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/f0ff/.config/Mailspring/keymap.json',
  filename: '/home/f0ff/.config/Mailspring/keymap.json' } { url: 'fs.js', line: 1396, column: 5, pluginIds: [] }
Raven: 429 - undefined
Raven: 429 - undefined
Created new window in existing browser session.
{ Error: watch /home/f0ff/.config/Mailspring/keymap.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at KeymapFile.watch (/src/keymap-manager.es6:83:8)
    at KeymapManager.loadKeymaps (/src/keymap-manager.es6:131:21)
    at window.requestAnimationFrame (/src/app-env.es6:596:26)
  message: 'watch /home/f0ff/.config/Mailspring/keymap.json ENOSPC',
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/f0ff/.config/Mailspring/keymap.json',
  filename: '/home/f0ff/.config/Mailspring/keymap.json' } { url: 'fs.js', line: 1396, column: 5, pluginIds: [] }
Raven: 429 - Creation of this event was denied due to rate limiting```

**Comment by gerhardveldman** [comment]
Same on Ubuntu 17.10, ENOSPC means that there is no space on the drive, so this must be a permission problem, running Mailspring as super user gets me past the problem, next problem (possibly related to being super user) however is that I get the keyring failed to start message

**Comment by lucysan** [comment]
Don't run it as root, strace it and see where it tries to read/write. I would do it, but already left office for the weekend. 

⁣Pozdrawiam/Sincerely,
Luca Bernardi

**Comment by AhmetOZER** [comment]
Try this command ```sh
chmod 777 .config/*```

**Comment by machinekoder** [comment]
Exactly the same problem on Debian after upgrading to 1.3.0

**Comment by thelittlebug** [comment]
same problem here (linux mint 18.04), the reason: to many inotify file watchers used from visual studio code
tmp solution -> close visual studio code
perm solution -> increase file watcher limit

**Comment by CodeMouse92** [comment]
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
