### ISSUE TITLE
Mailspring folder creation issue (possibly only on Davmail?)

### ISSUE THREAD

**Issue by raqua** [Foundry376/Mailspring#588]
##### What operating system are you using?
Linux Mint 18.3

##### What version of Mailspring are you using?
1.1.1

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Davmail + Exchange

When I start MailSpring using Davmail (local imap server that translates Exchange connection - works fine with Thunderbird) it gets stuck on "Looking for messages". Davmail produces error "Folder Mailspring not found".
After creating the Mailspring folder manually, it works fine. 

These are the logs from Davmail:

`2018-01-29 11:48:38,362 DEBUG [davmail.imap.ImapServer] davmail  - Connection from /127.0.0.1 on port 1143
2018-01-29 11:48:38,362 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:33340 
2018-01-29 11:48:38,401 DEBUG [ImapConnection-33340] davmail.exchange.ExchangeSession  - Test configuration status: 301
2018-01-29 11:48:38,401 DEBUG [ImapConnection-33340] davmail  - > * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE] IMAP4rev1 DavMail 4.8.0.3-2488 server ready
2018-01-29 11:48:38,401 DEBUG [ImapConnection-33340] davmail  - < LOGIN ********
2018-01-29 11:48:38,454 DEBUG [ImapConnection-33340] davmail.exchange.ExchangeSession  - Got session davmail.exchange.ews.EwsExchangeSession@5818d663 from cache
2018-01-29 11:48:38,535 INFO  [ImapConnection-33340] davmail.connection  - LOGON - 127.0.0.1:33340 xxxxx@xxxxx.sk
2018-01-29 11:48:38,535 DEBUG [ImapConnection-33340] davmail  - > 1 OK Authenticated
2018-01-29 11:48:38,547 DEBUG [ImapConnection-33340] davmail  - < 2 CAPABILITY
2018-01-29 11:48:38,547 DEBUG [ImapConnection-33340] davmail  - > * CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE
2018-01-29 11:48:38,548 DEBUG [ImapConnection-33340] davmail  - > 2 OK CAPABILITY completed
2018-01-29 11:48:38,592 DEBUG [ImapConnection-33340] davmail  - < 3 LIST "" ""
2018-01-29 11:48:38,633 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasChildren) "/" ""
2018-01-29 11:48:38,633 DEBUG [ImapConnection-33340] davmail  - > 3 OK LIST completed
2018-01-29 11:48:38,676 DEBUG [ImapConnection-33340] davmail  - < 4 LIST "" "*"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "_Confluence"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "_Important"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "_Read"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "Trash"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "Drafts"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "INBOX"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "Junk"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "Unsent Messages"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > * LIST (\HasNoChildren) "/" "Sent"
2018-01-29 11:48:38,721 DEBUG [ImapConnection-33340] davmail  - > 4 OK LIST completed
2018-01-29 11:48:38,865 DEBUG [ImapConnection-33340] davmail  - < 5 SELECT INBOX
2018-01-29 11:48:38,970 DEBUG [ImapConnection-33340] davmail  - > * 0 EXISTS
2018-01-29 11:48:38,970 DEBUG [ImapConnection-33340] davmail  - > * 0 RECENT
2018-01-29 11:48:38,970 DEBUG [ImapConnection-33340] davmail  - > * OK [UIDVALIDITY 1]
2018-01-29 11:48:38,970 DEBUG [ImapConnection-33340] davmail  - > * OK [UIDNEXT 1]
2018-01-29 11:48:38,970 DEBUG [ImapConnection-33340] davmail  - > * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk)
2018-01-29 11:48:38,970 DEBUG [ImapConnection-33340] davmail  - > * OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk \*)]
2018-01-29 11:48:38,970 DEBUG [ImapConnection-33340] davmail  - > 5 OK [READ-WRITE] SELECT completed
2018-01-29 11:48:39,062 DEBUG [ImapConnection-33340] davmail  - < 6 CREATE "Mailspring/Snoozed"
2018-01-29 11:48:39,119 ERROR [ImapConnection-33340] davmail  - Folder 'Mailspring' not found
davmail.exception.HttpNotFoundException: Folder 'Mailspring' not found
	at davmail.exchange.ews.EwsExchangeSession.getFolderId(EwsExchangeSession.java:2317)
	at davmail.exchange.ews.EwsExchangeSession.createFolder(EwsExchangeSession.java:1217)
	at davmail.exchange.ExchangeSession.createMessageFolder(ExchangeSession.java:1445)
	at davmail.imap.ImapConnection.run(ImapConnection.java:271)
2018-01-29 11:48:39,119 DEBUG [ImapConnection-33340] davmail  - > 6 BAD unable to handle request: Folder 'Mailspring' not found
2018-01-29 11:48:39,119 INFO  [ImapConnection-33340] davmail.connection  - DISCONNECT - 127.0.0.1:33340 
2018-01-29 11:48:39,120 DEBUG [davmail.imap.ImapServer] davmail  - Connection from /127.0.0.1 on port 1143
2018-01-29 11:48:39,120 INFO  [davmail.imap.ImapServer] davmail.connection  - CONNECT - 127.0.0.1:33348 
2018-01-29 11:48:39,201 DEBUG [ImapConnection-33348] davmail.exchange.ExchangeSession  - Test configuration status: 301
2018-01-29 11:48:39,201 DEBUG [ImapConnection-33348] davmail  - > * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE] IMAP4rev1 DavMail 4.8.0.3-2488 server ready
2018-01-29 11:48:39,201 DEBUG [ImapConnection-33348] davmail  - < LOGIN ********
2018-01-29 11:48:39,230 DEBUG [ImapConnection-33348] davmail.exchange.ExchangeSession  - Got session davmail.exchange.ews.EwsExchangeSession@5818d663 from cache
2018-01-29 11:48:39,264 INFO  [ImapConnection-33348] davmail.connection  - LOGON - 127.0.0.1:33348 Dratva@editel.sk
2018-01-29 11:48:39,264 DEBUG [ImapConnection-33348] davmail  - > 1 OK Authenticated
2018-01-29 11:48:39,295 DEBUG [ImapConnection-33348] davmail  - < 2 CAPABILITY
2018-01-29 11:48:39,295 DEBUG [ImapConnection-33348] davmail  - > * CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE
2018-01-29 11:48:39,296 DEBUG [ImapConnection-33348] davmail  - > 2 OK CAPABILITY completed
2018-01-29 11:48:39,343 DEBUG [ImapConnection-33348] davmail  - < 3 LIST "" ""
2018-01-29 11:48:39,408 DEBUG [ImapConnection-33348] davmail  - > * LIST (\HasChildren) "/" ""
2018-01-29 11:48:39,408 DEBUG [ImapConnection-33348] davmail  - > 3 OK LIST completed
2018-01-29 11:48:39,452 DEBUG [ImapConnection-33348] davmail  - < 4 STATUS INBOX (UNSEEN MESSAGES RECENT UIDNEXT UIDVALIDITY)
2018-01-29 11:48:39,517 DEBUG [ImapConnection-33348] davmail.imap.ImapConnection  - *
2018-01-29 11:48:39,545 DEBUG [ImapConnection-33348] davmail  - >  STATUS "INBOX" (UNSEEN 0 MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1)
2018-01-29 11:48:39,546 DEBUG [ImapConnection-33348] davmail  - > 4 OK STATUS completed
2018-01-29 11:48:39,588 DEBUG [ImapConnection-33348] davmail  - < 5 SELECT INBOX
2018-01-29 11:48:39,687 DEBUG [ImapConnection-33348] davmail  - > * 0 EXISTS
2018-01-29 11:48:39,687 DEBUG [ImapConnection-33348] davmail  - > * 0 RECENT
2018-01-29 11:48:39,687 DEBUG [ImapConnection-33348] davmail  - > * OK [UIDVALIDITY 1]
2018-01-29 11:48:39,687 DEBUG [ImapConnection-33348] davmail  - > * OK [UIDNEXT 1]
2018-01-29 11:48:39,687 DEBUG [ImapConnection-33348] davmail  - > * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk)
2018-01-29 11:48:39,687 DEBUG [ImapConnection-33348] davmail  - > * OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded Junk \*)]
2018-01-29 11:48:39,687 DEBUG [ImapConnection-33348] davmail  - > 5 OK [READ-WRITE] SELECT completed
2018-01-29 11:48:39,794 DEBUG [ImapConnection-33348] davmail  - < 6 UID FETCH 1 (UID FLAGS)
2018-01-29 11:48:39,833 DEBUG [ImapConnection-33348] davmail  - > 6 OK UID FETCH completed
`

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - Mailspring is trying to create a folder called `Mailspring/Snoozed` without first creating the containing folder. Usually this autogenerates the parent folder, but I guess it doesn't work with Davmail. I'll change the app so that it explicitly creates the parent folder.

**Comment by bengotow** [comment]
Hey folks—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!
