### ISSUE TITLE
TypeError: Cannot read property 'data' of null

### ISSUE THREAD

**Issue by victortrac** [Foundry376/Mailspring#693]
As I'm editing a reply, the right most column/panel crashes with this stacktrace:
```
TypeError: Cannot read property 'data' of null
    at FloatingEmojiPicker (/src/components/composer-editor/emoji-plugins.jsx:77:18)
    at beginWork (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:310)
    at d (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:93)
    at f (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:417)
    at g (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:173)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at vd (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:71:249)
```

##### What operating system are you using?
linux, gnome-shell

##### What version of Mailspring are you using?
1.1.4.22d9f20-1
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Just responding to emails in the editor. It feels like mid-typing. I have to completely quit out of the mailspring UI before the rightmost panel renders again.

**Comment by victortrac** [comment]
Duplicate of #685
