### ISSUE TITLE
GMail trouble to loggin in

### ISSUE THREAD

**Issue by ghost** [Foundry376/Mailspring#764]
I have trouble to log in with my google email account ... Verification on gmail site is OK, and finsihed with You're all set! but then mailspring had trouble to logging, hwo to fix it?

**Comment by zaaack** [comment]
Just hit this problem, too.

**Comment by zaaack** [comment]
Here is my error message:
```sh
/Applications/Mailspring.app/Contents/Resources/app.asar/src/error-logger.js:101 Error: An unexpected mailsync error occurred (null)
    at ChildProcess._proc.on.code (/src/mailsync-process.es6:194:25)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5) Object {pluginIds: Array(0)}
module.exports.ErrorLogger.reportError @ /Applications/Mailspring.app/Contents/Resources/app.asar/src/error-logger.js:101
reportError @ app-env.es6:233
_onError @ oauth-signin-page.jsx:82
_onReceivedCode @ oauth-signin-page.jsx:94
_tickDomainCallback @ internal/process/next_tick.js:228

```

**Comment by bengotow** [comment]
Hey folks! Hmm this one's new - will see if I can narrow this down.

**Comment by Petur06** [comment]
Same here.
Win 7, behind corporate proxy (if that's any help).

**Comment by mcfans** [comment]
@zaaack @peter73421  I found a workaround for this on macOS.I think that issue is a proxy problem.I am using proxy to access google, But it seems this app didn't use that proxy, So I used one app called Proxifier to force this app access network bypass that proxy, and it works.The Unibox.app has exactly the same problem, it looks like my proxy didn't work for IMAP

**Comment by CodeMouse92** [comment]
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
