### ISSUE TITLE
TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.

### ISSUE THREAD

**Issue by BenoitDuffez** [Foundry376/Mailspring#786]
##### What operating system are you using?
 Elementary OS loki 0.4.1 (Ubuntu 16.04)

##### What version of Mailspring are you using?
1.1.5-5834c99f through snapd

##### Do you have any third-party plugins installed? If so, which ones?
none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't think so

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![2018-03-26_15-03-51_screenshot](https://user-images.githubusercontent.com/802209/37909792-25683340-310c-11e8-9181-6f0cbaa444b0.png)
moved three mails from one folder to another (drag and drop), then tried to read a mail...
I have restarted the application but the red box persisted.
Switching from dual pane to single pane, then dual pane again fixed the issue.

Since it is restored, you can close the issue, but I figured you may want to receive feedback on such errors (as a developer I know I would).

Thanks for the app,
Cheers!

**Comment by 10robinho** [comment]
Same issue here, Ubuntu 16.04.2 LTS and Mailspring 1.1.15

Sometimes switching read panel off and on fixes issue, but I've seen cases where there is no way to fix it so I have to read that specific email in other client.

This is error I receive:

> TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.
    at QuotedHTMLTransformer._removeImagesStrippedByAnotherClient (/src/services/quoted-html-transformer.es6:62:24)
    at QuotedHTMLTransformer.removeQuotedHTML (/src/services/quoted-html-transformer.es6:55:10)
    at EmailFrame._emailContent (/internal_packages/message-list/lib/email-frame.jsx:59:34)
    at EmailFrame._writeContent (/internal_packages/message-list/lib/email-frame.jsx:83:72)
    at EmailFrame.componentDidMount (/internal_packages/message-list/lib/email-frame.jsx:27:10)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168

**Comment by adolson** [comment]
I get this once in a while, too. I have to close and reopen it. Seems like certain emails trigger it, so I have to delete them and can't read them.

I use Debian Stable and always update Mailspring when there's an update notification in the bottom left corner.

**Comment by bengotow** [comment]
Hey folks thanks for collecting these - if anyone runs into this again, could you post an updated stack trace? It looks like that scenario above is probably taken care of in recent builds, but you might be seeing something similar (but with a different trace.)

**Comment by 10robinho** [comment]
I updated to 1.2.1 and I encountered this error again, here is stack trace now:

```
TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.
    at QuotedHTMLTransformer._removeImagesStrippedByAnotherClient (/src/services/quoted-html-transformer.es6:62:24)
    at QuotedHTMLTransformer.removeQuotedHTML (/src/services/quoted-html-transformer.es6:55:10)
    at EmailFrame._emailContent (/internal_packages/message-list/lib/email-frame.jsx:59:34)
    at EmailFrame._writeContent (/internal_packages/message-list/lib/email-frame.jsx:83:72)
    at EmailFrame.componentDidMount (/internal_packages/message-list/lib/email-frame.jsx:27:10)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at u (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
    at MessageItemBody.A.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.production.min.js:12:357)
    at _unsub._mailspringExports.MessageBodyProcessor.subscribe.processedBody (/internal_packages/message-list/lib/message-item-body.jsx:63:29)
    at retrieve.then.output (/src/flux/stores/message-body-processor.es6:97:13)
    at <anonymous>
```

**Comment by adolson** [comment]
Same here:

TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.
    at QuotedHTMLTransformer._removeImagesStrippedByAnotherClient (/src/services/quoted-html-transformer.es6:62:24)
    at QuotedHTMLTransformer.removeQuotedHTML (/src/services/quoted-html-transformer.es6:55:10)
    at EmailFrame._emailContent (/internal_packages/message-list/lib/email-frame.jsx:59:34)
    at EmailFrame._writeContent (/internal_packages/message-list/lib/email-frame.jsx:83:72)
    at EmailFrame.componentDidMount (/internal_packages/message-list/lib/email-frame.jsx:27:10)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at u (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
    at MessageItemBody.A.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.production.min.js:12:357)
    at _unsub._mailspringExports.MessageBodyProcessor.subscribe.processedBody (/internal_packages/message-list/lib/message-item-body.jsx:63:29)
    at retrieve.then.output (/src/flux/stores/message-body-processor.es6:97:13)
    at <anonymous>

**Comment by budparr** [comment]
Getting this error, too. Version 1.2.1 (1.2.1)

```
TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.
    at QuotedHTMLTransformer._removeImagesStrippedByAnotherClient (/src/services/quoted-html-transformer.es6:62:24)
    at QuotedHTMLTransformer.removeQuotedHTML (/src/services/quoted-html-transformer.es6:55:10)
    at EmailFrame._emailContent (/internal_packages/message-list/lib/email-frame.jsx:59:34)
    at EmailFrame._writeContent (/internal_packages/message-list/lib/email-frame.jsx:83:72)
    at EmailFrame.componentDidMount (/internal_packages/message-list/lib/email-frame.jsx:27:10)
```

**Comment by 10robinho** [comment]
I can confirm no improvements here, I tried on windows and other linux distros too.
It's basically making Mailspring unusable for large email threads.

**Comment by datasage** [comment]
I've gotten the same error on macos client. It happens for specific messages, but once it happens i can't view any messages without restarting.

**Comment by CodeMouse92** [comment]
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
