### ISSUE TITLE
Error when opening mails from Outlook

### ISSUE THREAD

**Issue by apatrascu** [Foundry376/Mailspring#789]
##### Are there any related issues?

No

##### What operating system are you using?
Ubuntu 16.04, kernel 4.13.0-36-generic

##### What version of Mailspring are you using?
1.1.5-5834c99f

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only use Outlook email provider (from a 360 subscription)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

For all my messages, when I click to read them, in the preview pane I see in red this:
```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (155).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:308)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
```
If I double click the email, a new window pops up and the message displays just fine.

**Comment by CodeMouse92** [comment]
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
