### ISSUE TITLE
Raven: 429 - Creation of this event was denied due to rate limiting

### ISSUE THREAD

**Issue by sikand** [Foundry376/Mailspring#905]
##### Are there any related issues?

...

##### What operating system are you using?
Linux
...

##### What version of Mailspring are you using?
linux/x64/1.2.2-96fb3a99/1d60dd13-c553-49b0-a84b-532193a10524/stable

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
no

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:308)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at vd (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:71:249) { pluginIds: [] }
Raven: 429 - Creation of this event was denied due to rate limiting

**Comment by sikand** [comment]
Unable to reproduce in newer builds
