### ISSUE TITLE
Cannot view tracking details

### ISSUE THREAD

**Issue by FirewaII** [Foundry376/Mailspring#945]
##### What operating system are you using?
Ubuntu, WIndows 10 and Arch Linux

##### What version of Mailspring are you using?
v 1.2.2-96fb3a99

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins installed

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
It concerns all email providers. I have tried Gmail, O365 and IMAP.

##### The issue
Details window when trying to view tracking details in an email (purple eye with X opens) does not show up like it used to.
I have tried to launch Mailspring from a terminal and this is the log output I get when doing so:

<pre>{ TypeError: _activityEventStore2.default.getRecipient is not a function
    at opens.map.open (/internal_packages/open-tracking/lib/open-tracking-message-popover.jsx:20:44)
    at Array.map (native)
    at OpenTrackingMessagePopover.renderOpenActions (/internal_packages/open-tracking/lib/open-tracking-message-popover.jsx:15:18)
    at OpenTrackingMessagePopover.render (/internal_packages/open-tracking/lib/open-tracking-message-popover.jsx:37:55)
    at h (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:130:280)
    at beginWork (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:485)
    at d (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:93)
    at f (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:161:417)
    at g (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at m (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:173)
    at w (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at vd (/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:71:249)
  message: &apos;_activityEventStore2.default.getRecipient is not a function&apos; } { url: &apos;/snap/mailspring/216/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js&apos;,
  line: 168,
  column: 489,
  pluginIds: [ &apos;open-tracking&apos; ] }
</pre>

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—good catch. I'll get this fixed in the next release which is due out any day now.

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
