### ISSUE TITLE
Error while composing a reply message

### ISSUE THREAD

**Issue by RyanNerd** [Foundry376/Mailspring#957]
##### What operating system are you using?
Linux Mint 18.2 64-bit Intel

##### What version of Mailspring are you using?
1.2.2-96fb3a99

--

Possibly related to #950 

--

**Bug?**
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidMount (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:113:13)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at u (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
    at _class.A.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.production.min.js:12:357)
```

**Comment by interactiveRob** [comment]
+1 
This keeps happening to me too. 
I'm on Mac OSX 10.13.6 
Using Mailspring version 1.5.3 (1.5.3)
Here's the error I got: 
```

Error: Failed to execute 'setStart' on 'Range': The offset 4294967294 is larger than the node's length (1).
    at findDOMRange (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at Hi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:383)
    at Fi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at Ki (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232:135)
    at de (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)
```

**Comment by bengotow** [comment]
Merging this in to #921
